# festivals-website-node configuration file v1.0
# TOML 1.0.0-rc.2+

[service]
bind-host = "website-0.festivalsapp.dev"
port = 48155
key = "TEST_SERVICE_KEY_001"

[tls]
festivaslapp-root-ca = "~/Library/Containers/org.festivalsapp.project/usr/local/festivals-website-node/ca.crt"
cert = "~/Library/Containers/org.festivalsapp.project/usr/local/festivals-website-node/server.crt"
key = "~/Library/Containers/org.festivalsapp.project/usr/local/festivals-website-node/server.key"

[heartbeat]
endpoint = "https://discovery.festivalsapp.dev:8443/loversear"
interval = 6

[authentication]
endpoint = "https://identity.festivalsapp.dev:22580"

[website]
bind-host = "festivalsapp.dev"
port = 8080
protocol = "https"

[log]
info = "~/Library/Containers/org.festivalsapp.project/var/log/festivals-website-node/info.log"
trace = "~/Library/Containers/org.festivalsapp.project/var/log/festivals-website-node/trace.log"