# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on: 
  release:
    types: [ created ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    
      - name: Step 1 - Prepare build environment
        run: sudo apt install minify -y
    
      - name: Step 2 - Compile website
        run: ./compile.sh
        
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: build/current
