# Publish GitHub workflow artifacts tutorial example
name: Release website

on: 
  release:
    types: [ created ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Step 1 - Prepare compile environment
        run: sudo apt install minify -y
    
      - name: Step 2 - Compile website
        run: |
          chmod +x compile.sh
          ./compile.sh
          
      - name: Step 3 - Create version file
        run: |
          cd build/current 
          echo "$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )" >> version
      
      - name: Step 4 - Create compile_date file
        run: |
          cd build/current
          echo "$(date)" >> compile_date
        
      - name: Step 5 - Tar and compress
        run: |
          cd build/current
          tar -zcvf festivals-website.tar.gz * .well-known
          
      - name: Step 6 - Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/current/festivals-website.tar.gz
          tag: ${{ github.ref }}
